apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-demo-app
  template:
    metadata:
      labels:
        app: db-demo-app
    spec:
      containers:
        # List all the containers for the deployment
        - name: db-demo-app
          image: naineelsoyantar/express-db-demo:2
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: express-db-demo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: express-db-demo-config
                  key: MONGO_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: db-demo-app-service
spec:
  type: LoadBalancer
  selector:
    app: db-demo-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
