apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-imagepull-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-imagepull
  template:
    metadata:
      labels:
        app: private-imagepull
    spec:
      containers:
      - name: private-imagepull-container
        image: naineel1209/winston-logger-server:v1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-registry-secret
