apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAiYXV0aCI6IHsNCiAgICAiZG9ja2VyLmlvIjogew0KICAgICAgInVzZXJuYW1lIjogIm5haW5lZWwxMjA5IiwNCiAgICAgICJwYXNzd29yZCI6ICJkY2tyX3BhdF9haFV4VmJiYm1HUDdXTWJzZXdqQzVCa3B0NVUiLA0KICAgICAgImVtYWlsIjogIm5haW5lZWxzb3lhbnRhckBnbWFpbC5jb20iDQogICAgfQ0KICB9DQp9DQo=
