apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-file-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-file-demo
  template:
    metadata:
      labels:
        app: node-file-demo
    spec:
      containers:
        - name: node-file-demo
          image: philippaul/node-file-demo:01
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: myvol
              mountPath: /app/emails.txt
      volumes:
        - name: myvol
          hostPath:
            path: /emails.txt
            type: FileOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: node-file-demo-service
spec:
  type: LoadBalancer
  selector:
    app: node-file-demo
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
