apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: first-configmap
              key: username
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: first-configmap
              key: database
        - name: MYSQL_PASSWORD
          value: "1234567890"  # Specify a strong password.
        - name: MYSQL_ROOT_PASSWORD
          value: "1234567890" # You should change this value.
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-storage
      emptyDir: {}
